from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
img1 = img.open('../img/rgb.jpg').convert('RGB')
np1 = np.array(img1)
img2 = io.imread('../img/rgb.jpg')
print(np1)
print('查看形狀目前是np1')
print(np1.shape)
print('查看形狀目前是img1')
print(img1.size)
print('顯示1,1的色彩資訊目前是np1')
print(np[1, 1, :])
print('顯示1,1的色彩資訊目前是img1')
print(img1.getpixel(1, 1))
print('個別顯示1,1 RGB顏色資訊')
print('紅色:', np1[1, 1, 0])
print('綠色:', np1[1, 1, 1])
print('藍色:', np1[1, 1, 2])
print('分別顯示此圖RGB資訊- np1')
print('R:', np1[:, :, 0])
print('G:', np1[:, :, 1])
print('B:', np1[:, :, 2])
print('分別顯示此圖RGB資訊- img1')
print('R:', np.array(img1.getchannel(0)))
print('G:', np.array(img1.getchannel(1)))
print('B:', np.array(img1.getchannel(2)))

print(img2)
print(img2.size)
print(img2[1, 1, :])
print('紅色:', img2[1, 1, 0])
print('綠色:', img2[1, 1, 1])
print('藍色:', img2[1, 1, 2])
print('R:', img2[:, :, 0])
print('G:', img2[:, :, 1])
print('B:', img2[:, :, 2])
