import cv2
img = cv2.imread('../img/Flower.bmp')
a = cv2.Laplacian(img, cv2.CV_16S, ksize = 1)
x1 = cv2.convertScaleAbs(a)
b = cv2.Laplacian(img, cv2.CV_16S, ksize = 3)
x3 = cv2.convertScaleAbs(b)
c = cv2.Laplacian(img, cv2.CV_16S, ksize = 5)
x5 = cv2.convertScaleAbs(c)
d = cv2.Laplacian(img, cv2.CV_16S, ksize = 7)
x7 = cv2.convertScaleAbs(d)
cv2.imshow('x1', x1)
cv2.imshow('x3', x3)
cv2.imshow('x5', x5)
cv2.imshow('x7', x7)
cv2.waitKey(0)