import cv2
img = cv2.imread('../img/graph2.png')
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
gray = cv2.GaussianBlur(gray, (11,11), 0)
gray = cv2.Canny(gray, 100, 300)
ret, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(img, contours, -1, (0, 0, 255), 3)
cv2.imshow('try1', img)
#cv2.imwrite('threshold1.png', img)
cv2.waitKey()