import numpy as np
import cv2,os
from skimage import io
def diplayIMG(img, windowName):
    cv2.namedWindow(windowName, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(windowName, 400, 300)
    cv2.imshow(windowName, img)
image = cv2.imread('../img/office.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
diplayIMG(image, 'Original')
sobelX = cv2.Sobel(image, cv2.CV_16S, 1 ,0)
sobelY = cv2.Sobel(image, cv2.CV_16S, 0 ,1)
sobelXY = cv2.Sobel(image, cv2.CV_16S, 1 ,1)
LaplacianXY = cv2.Laplacian(image, cv2.CV_16S,ksize = 1)
sobelX = cv2.convertScaleAbs(sobelX)
sobelY = cv2.convertScaleAbs(sobelY)
sobelXY = cv2.convertScaleAbs(sobelXY)
LaplacianXY = cv2.convertScaleAbs(LaplacianXY)
diplayIMG(sobelX, 'sobelX')
diplayIMG(sobelY, 'sobelY')
diplayIMG(sobelXY, 'sobelXY')
sobelCombined = cv2.bitwise_or(sobelX, sobelY)
diplayIMG(sobelCombined, 'sobelCombined')
diplayIMG(LaplacianXY, 'LaplacianXY')
canny1 = cv2.Canny(image, 30 ,170)
canny2 = cv2.Canny(image, 90, 170)
canny3 = cv2.Canny(image, 150, 170)
diplayIMG(canny1, 'canny1')
diplayIMG(canny2, 'canny2')
cv2.waitKey()